import test from "node:test";
import assert from "node:assert/strict";
import {emptyData,today,dateShift,calculateReport,balance,type Actor,type LedgerData} from "../lib/model";
import {applyOperation,visibleData} from "../lib/operations";
import {parseIntent} from "../lib/intents";
const actor:Actor={userId:"owner",name:"Test owner",email:"owner@example.test",role:"Super admin",customerId:"",permissions:[]};
const now=today();
function fixture(){const d=emptyData();d.customers=[{id:"c1",name:"Test customer",email:"customer@example.test",phone:"",island:"Malé",address:"",business:"",tier:"Retail",limit:10000,approved:true,created:now}];d.products=[{id:"p1",name:"Test diesel",code:"TEST-1",category:"Fuel",price:10,cost:6,stock:100,reorder:5,unit:"L",barcode:"",rates:{Retail:10}}];return d}
function run(d:LedgerData,type:string,payload:Record<string,unknown>,a=actor){return applyOperation(d,a,{type,payload,requestId:crypto.randomUUID()})}
const sale=(extra:Record<string,unknown>={})=>({customerId:"c1",date:now,due:dateShift(now,14),method:"Credit",discount:0,vat:0,items:[{productId:"p1",qty:10}],...extra});
test("invoice, stock, delivery and initial cash payment update together",()=>{const original=fixture();const {data}=run(original,"sale",sale({method:"Cash",discount:10,vat:10}));assert.equal(data.invoices[0].total,99);assert.equal(data.products[0].stock,90);assert.equal(data.payments[0].amount,99);assert.equal(data.deliveries[0].invoiceId,data.invoices[0].id);assert.equal(original.products[0].stock,100)});
test("overselling duplicate product lines fails without changing original data",()=>{const d=fixture();assert.throws(()=>run(d,"sale",sale({items:[{productId:"p1",qty:60},{productId:"p1",qty:60}]})),/available/);assert.equal(d.invoices.length,0);assert.equal(d.products[0].stock,100)});
test("credit limits block excessive sales",()=>{const d=fixture();d.customers[0].limit=99;assert.throws(()=>run(d,"sale",sale()),/credit/)});
test("partial payments match invoice and report balances",()=>{let {data}=run(fixture(),"sale",sale());data=run(data,"payment",{invoiceId:data.invoices[0].id,date:now,amount:30,method:"Cash"}).data;assert.equal(balance(data,"c1"),70);assert.equal(calculateReport(data,{from:now,to:now}).outstanding,70);assert.throws(()=>run(data,"payment",{invoiceId:data.invoices[0].id,date:now,amount:70.01,method:"Cash"}),/remaining balance/)});
test("fractional cents and unrepresentable stock quantities are rejected",()=>{let {data}=run(fixture(),"sale",sale());assert.throws(()=>run(data,"payment",{invoiceId:data.invoices[0].id,date:now,amount:.005,method:"Cash"}));assert.throws(()=>run(fixture(),"sale",sale({items:[{productId:"p1",qty:.001}]})))});
test("collections use payment date while historical balances use the report end",()=>{const date=dateShift(now,-10);let {data}=run(fixture(),"sale",sale({date}));data=run(data,"payment",{invoiceId:data.invoices[0].id,date:now,amount:40,method:"Bank transfer"}).data;const past=calculateReport(data,{from:date,to:date});const current=calculateReport(data,{from:now,to:now});assert.equal(past.sales,100);assert.equal(past.collections,0);assert.equal(past.outstanding,100);assert.equal(current.sales,0);assert.equal(current.collections,40);assert.equal(current.outstanding,60)});
test("same-day fuel sales refresh existing meter reconciliation",()=>{let {data}=run(fixture(),"reading",{productId:"p1",date:now,start:100,end:110,notes:""});assert.equal(data.readings[0].difference,10);data=run(data,"sale",sale()).data;assert.equal(data.readings[0].difference,0);assert.equal(calculateReport(data,{from:now,to:now}).meterDifference,0)});
test("sales staff cannot override assigned rates or edit products",()=>{const staff={...actor,role:"Sales staff" as const};assert.throws(()=>run(fixture(),"sale",sale({items:[{productId:"p1",qty:1,price:1}]}),staff),/assigned/);assert.throws(()=>run(fixture(),"product",{},staff),/permission/)});
test("customer data is scoped and cannot post to another account",()=>{let {data}=run(fixture(),"sale",sale());const customer={...actor,role:"Customer" as const,customerId:"c2"};const view=visibleData(data,customer);assert.equal(view.invoices.length,0);assert.equal(view.customers.length,0);assert.equal(view.payments.length,0);assert.equal(view.audit.length,0);assert.throws(()=>run(data,"comment",{invoiceId:data.invoices[0].id,text:"hello"},customer),/not found/)});
const ranges:[string,string,string][]=[["report from 2026-09-01 to 2026-09-15","2026-09-01","2026-09-15"],["report from 1 September 2026 to 15 September 2026","2026-09-01","2026-09-15"],["report last 7 days through today","2026-09-09","2026-09-15"],["report last month","2026-08-01","2026-08-31"],["report last year","2025-01-01","2025-12-31"],["report for Jan","2026-01-01","2026-01-31"],["report this week","2026-09-14","2026-09-15"]];
for(const [prompt,from,to] of ranges)test("date range: "+prompt,()=>{const result=parseIntent(prompt,"2026-09-15");assert.equal(result.type,"report");if(result.type==="report")assert.deepEqual({from:result.filters.from,to:result.filters.to},{from,to})});
for(const prompt of ["report 2026-02-30","report 2026-09-01 to 09/15/2026","report from 2026-09-15 to 2026-09-01","report this quarter","report from 1 September to 15","report 03/04/2026"])test("clarify invalid or ambiguous dates: "+prompt,()=>assert.equal(parseIntent(prompt,"2026-09-15").type,"clarify"));
