"use client";
import {useState} from "react";
import {Plus,Trash2,LoaderCircle,Package,Check} from "lucide-react";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Switch} from "@/components/ui/switch";
import {Checkbox} from "@/components/ui/checkbox";
import {Choice,Field,type AppCtx} from "./ui";
import {today,dateShift,money,outstanding,customerName,balance,round,permissions} from "@/lib/model";
import {maldivesIslands} from "@/lib/islands";
const titles:Record<string,string>={sale:"New sale",customer:"Customer details",product:"Product details",payment:"Record a payment",delivery:"Update delivery",order:"Purchase order",orderRequest:"Request an order",reading:"Add fuel reading",credit:"Manage customer credit",member:"Team member",expense:"Record an expense"};
export function EntryDialog({type,record,onClose,ctx}:{type:string;record:any;onClose:()=>void;ctx:AppCtx}){
 const [error,setError]=useState("");const [saving,setSaving]=useState(false);const [values,setValues]=useState<Record<string,any>>(()=>({...record,date:record?.date||today(ctx.data.business.timeZone),due:dateShift(today(ctx.data.business.timeZone),14),method:"Cash",tier:"Retail",status:record?.status||"Pending",customerId:record?.customerId||(type==="credit"?record?.id:ctx.actor.customerId||""),role:record?.role||"Sales staff",approved:record?.approved??true,permissions:record?.permissions||[]}));
 const [lines,setLines]=useState<{productId:string;qty:number;price?:number}[]>([{productId:"",qty:1}]);const [phoneLocal,setPhoneLocal]=useState(()=>String(record?.phone||"").replace(/^\+?960[\s-]*/,"").trim());const d=ctx.data;
 const set=(key:string,value:any)=>setValues(v=>({...v,[key]:value}));
 const input=(name:string,label:string,kind="text",initial:any="",required=true,wide=false)=><Field label={label} wide={wide}><input name={name} type={kind} defaultValue={record?.[name]??initial} required={required} min={kind==="number"?0:undefined} step={kind==="number"?"0.01":undefined} maxLength={kind==="text"?500:undefined}/></Field>;
 const choice=(name:string,label:string,options:any[],fallback?:string)=><Field label={label}><Choice label={label} name={name} value={values[name]??fallback} onChange={v=>set(name,v)} options={options}/></Field>;
 const customerOptions=d.customers.map(c=>({value:c.id,label:c.name}));const productOptions=d.products.map(p=>({value:p.id,label:p.name+" · "+p.stock+" "+p.unit+" available"}));
 const invoice=d.invoices.find(i=>i.id===(values.invoiceId||record?.invoiceId));const customer=d.customers.find(c=>c.id===values.customerId);
 const selectedLine=(l:typeof lines[number])=>{const p=d.products.find(p=>p.id===l.productId);return{p,price:l.price??p?.rates[customer?.tier||"Retail"]??p?.price??0}};
 const subtotal=round(lines.reduce((s,l)=>s+l.qty*selectedLine(l).price,0)),discount=Number(values.discount||0),vat=Number(values.vat??d.business.vat),total=round(Math.max(0,subtotal-discount)*(1+vat/100));
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(saving)return;setSaving(true);setError("");try{const form=Object.fromEntries(new FormData(e.currentTarget));let payload:Record<string,unknown>={...form,...values};if(record?.id)payload.id=record.id;
  // Text/number inputs use native FormData; controlled selectors and switches use values.
  payload={...values,...form};if(record?.id)payload.id=record.id;
  if(type==="sale")payload={...payload,customerId:values.customerId,method:values.method,items:lines.map(l=>({...l,price:selectedLine(l).price})),discount,vat};
  if(type==="product")payload.rates=Object.fromEntries(["Wholesale","VIP","Contractor","School"].map(t=>[t,Number(form["rate_"+t]||form.price)]));
  if(type==="credit")payload={customerId:record?.id||values.customerId,limit:form.limit,approved:values.approved};
  if(type==="payment")payload.invoiceId=values.invoiceId||record?.invoiceId;
  if(type==="member")payload.permissions=values.permissions;
  if(type==="customer")payload.phone=(values.phone||"").toString();
  if(type==="orderRequest")payload.customerId=ctx.actor.customerId;
  const result=await ctx.save(type,payload);onClose();if(type==="sale"&&result?.id)ctx.openInvoice(result.id);
 }catch(err){setError(err instanceof Error?err.message:"Unable to save. Please try again.")}finally{setSaving(false)}}
 return <Dialog open onOpenChange={open=>{if(!open&&!saving)onClose()}}><DialogContent className={"ledger-dialog "+(type==="sale"?"sale-dialog":"")}><DialogHeader><DialogTitle>{titles[type]||"Add record"}</DialogTitle><DialogDescription>{type==="sale"?"Create an invoice and delivery note. Stock and credit update when you save.":"Check the details below, then save your changes."}</DialogDescription></DialogHeader><form onSubmit={submit}><div className="form-grid">
 {type==="sale"&&<>{choice("customerId","Customer",customerOptions)}{choice("method","Payment method",["Cash","Bank transfer","Credit"],"Cash")}{input("date","Invoice date","date",values.date)}{input("due","Due date","date",values.due)}{input("po","Purchase order number","text","",false)}{input("remarks","Remarks","text","",false)}<div className="wide sale-items"><div className="line-labels"><span>Product</span><span>Qty</span><span>Unit price</span><span/></div>{lines.map((l,n)=><div className="sale-line" key={n}><Choice label={"Product "+(n+1)} value={l.productId||undefined} options={productOptions} onChange={v=>setLines(prev=>prev.map((x,i)=>i===n?{...x,productId:v,price:undefined}:x))}/><input aria-label={"Quantity "+(n+1)} type="number" min="0.01" step="0.01" value={l.qty} onChange={e=>setLines(prev=>prev.map((x,i)=>i===n?{...x,qty:Number(e.target.value)}:x))}/><input aria-label={"Unit price "+(n+1)} type="number" min="0" step="0.01" value={selectedLine(l).price} onChange={e=>setLines(prev=>prev.map((x,i)=>i===n?{...x,price:Number(e.target.value)}:x))}/><button type="button" className="icon-button" aria-label={"Remove line "+(n+1)} disabled={lines.length===1} onClick={()=>setLines(prev=>prev.filter((_,i)=>i!==n))}><Trash2 size={16}/></button></div>)}<button className="btn text" type="button" onClick={()=>setLines([...lines,{productId:"",qty:1}])}><Plus size={14}/>Add product</button></div><Field label={"Discount ("+d.business.currency+")"}><input type="number" min="0" max={subtotal} step="0.01" value={discount} onChange={e=>set("discount",e.target.value)}/></Field><Field label="VAT (%)"><input type="number" min="0" max="100" step="0.01" value={vat} onChange={e=>set("vat",e.target.value)}/></Field><div className="wide sale-total"><span>Invoice total</span><strong>{d.business.currency} {money(total)}</strong></div>{customer&&values.method==="Credit"&&<div className="wide form-note">Available credit: {d.business.currency} {money(Math.max(0,customer.limit-balance(d,customer.id)))} · {customer.tier} pricing</div>}</>}
 {type==="customer"&&<>{input("name","Customer name")}{input("business","Business name","text","",false)}<Field label="Phone number"><div style={{display:"flex",alignItems:"stretch",border:"1px solid #dfe6eb",borderRadius:7,overflow:"hidden"}}><span style={{padding:"10px 12px",background:"#f2f6f7",color:"#5b6b76",fontSize:14,borderRight:"1px solid #dfe6eb",whiteSpace:"nowrap"}}>+960</span><input type="tel" inputMode="numeric" value={phoneLocal} placeholder="777 1234" onChange={e=>{const v=e.target.value.replace(/[^\d ]/g,"").slice(0,15);setPhoneLocal(v);set("phone",v.trim()?"+960 "+v.trim():"")}} style={{border:"0",borderRadius:"0",flex:1,minWidth:0}}/></div></Field>{input("email","Email","email","",false)}<Field label="Island / city"><input name="island" list="maldives-islands" defaultValue={record?.island??""} placeholder="Start typing an island or city…" required maxLength={500}/></Field><datalist id="maldives-islands">{maldivesIslands.map(x=><option key={x} value={x}/>)}</datalist>{input("address","Address","text","",false)}{choice("tier","Price group",["Retail","Wholesale","VIP","Contractor","School"],"Retail")}{input("limit","Credit limit","number",0)}</>}
 {type==="product"&&<>{input("name","Product name")}{input("code","Product code")}{choice("category","Category",["Fuel","Building materials","Automotive","Stationery","Grocery","Other"],record?.category||"Other")}{input("unit","Unit","text","piece")}{input("cost","Cost price","number",0)}{input("price","Retail price","number",0)}{input("stock","Stock quantity","number",0)}{input("reorder","Reorder level","number",0)}{input("barcode","Barcode","text","",false)}<div className="wide"><h3 className="form-section-title">Customer pricing</h3><p className="subheading">Leave a rate empty to use the retail price.</p></div>{["Wholesale","VIP","Contractor","School"].map(t=><Field label={t+" price"} key={t}><input name={"rate_"+t} type="number" min="0" step="0.01" defaultValue={record?.rates?.[t]??""}/></Field>)}</>}
 {type==="payment"&&<>{choice("invoiceId","Invoice",d.invoices.filter(i=>outstanding(i)>0).map(i=>({value:i.id,label:i.number+" · "+customerName(d,i.customerId)})),record?.invoiceId)}{choice("method","Payment method",["Cash","Bank transfer"],"Cash")}{input("date","Payment date","date",values.date)}{input("amount","Amount received","number",invoice?outstanding(invoice):"")}{input("reference","Payment reference","text","",false,true)}{invoice&&<div className="wide form-note">Balance due: {d.business.currency} {money(outstanding(invoice))}</div>}</>}
 {type==="delivery"&&<>{choice("status","Delivery status",["Preparing","In transit","Delivered"],record?.status)}{input("vehicle","Vehicle registration","text","",false)}{input("driver","Driver name","text","",false)}{input("signature","Received by / signature name","text","",false)}</>}
 {(type==="order"||type==="orderRequest")&&<>{input("number","PO / order reference","text","PO-"+String(Date.now()).slice(-6))}{type!=="orderRequest"&&choice("customerId","Customer",customerOptions)}{input("date","Order date","date",values.date)}{input("amount","Order amount","number",0)}{type==="order"&&choice("status","Status",["Pending","Approved","Fulfilled","Cancelled"],"Pending")}{input("notes","Order details","text","",true,true)}</>}
 {type==="reading"&&<>{input("date","Business date","date",values.date)}{choice("productId","Fuel product",d.products.filter(p=>p.category==="Fuel").map(p=>({value:p.id,label:p.name})))}<Field label="Opening meter (L)"><input name="start" type="number" min="0" step="0.01" required value={values.start??""} onChange={e=>set("start",e.target.value)}/></Field><Field label="Closing meter (L)"><input name="end" type="number" min="0" step="0.01" required value={values.end??""} onChange={e=>set("end",e.target.value)}/></Field>{input("notes","Notes / meter discrepancy","text","",false,true)}<div className="wide sale-total"><span>Meter sales</span><strong>{money(Number(values.end||0)-Number(values.start||0))} L</strong></div><div className="wide form-note">Ledger compares these liters with invoices for this fuel product on the same date.</div></>}
 {type==="credit"&&<>{input("limit","Credit limit ("+d.business.currency+")","number",record?.limit||0)}<Field label="Credit access"><span className="switch-label"><Switch checked={values.approved} onCheckedChange={v=>set("approved",v)}/>{values.approved?"Approved":"Blocked"}</span></Field><div className="wide form-note">Current balance: {d.business.currency} {money(balance(d,record?.id||values.customerId))}. Sales that exceed the limit will be blocked.</div></>}
 {type==="expense"&&<>{input("date","Expense date","date",values.date)}{choice("category","Category",["Transport","Utilities","Rent","Supplies","Other"],"Other")}{input("amount","Amount","number",0)}{input("notes","Description","text","",true)}</>}
 {type==="member"&&<>{input("name","Full name")}{input("email","Sign-in email","email")}{choice("role","Role",["Manager","Sales staff","Accounts","Customer"],"Sales staff")}{values.role==="Customer"&&choice("customerId","Linked customer",customerOptions)}<div className="wide permission-box"><strong>{values.role} access</strong><p>{permissions[values.role as keyof typeof permissions].join(", ")}</p>{values.role!=="Customer"&&<><p>Additional permissions</p><div className="permission-grid">{["product","credit","report","sale","member"].filter(p=>!permissions[values.role as keyof typeof permissions].includes(p)).map(p=><label key={p}><Checkbox checked={values.permissions.includes(p)} onCheckedChange={v=>set("permissions",v?[...values.permissions,p]:values.permissions.filter((x:string)=>x!==p))}/>{p==="member"?"Manage users":p}</label>)}</div></>}</div><div className="wide form-note">Members sign in with ChatGPT using this email. The hosted site's audience must also allow them access. Adding a member does not send a message.</div></>}
 </div>{error&&<div role="alert" className="form-error">{error}</div>}<div className="form-actions"><button type="button" className="btn" onClick={onClose} disabled={saving}>Cancel</button><button type="submit" className="btn primary" disabled={saving}>{saving?<LoaderCircle size={16} className="spin"/>:<Check size={16}/>} {saving?"Saving…":type==="sale"?"Create invoice":type==="payment"?"Record payment":"Save changes"}</button></div></form></DialogContent></Dialog>
}
