"use client";
import {type ReactNode} from "react";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from "@/components/ui/empty";
import {Check,PackageOpen} from "lucide-react";
import {type Actor,type LedgerData,type ReportFilters} from "@/lib/model";
export type AppCtx={data:LedgerData;actor:Actor;save:(type:string,payload:Record<string,unknown>)=>Promise<any>;navigate:(page:string,filter?:string,query?:string)=>void;openForm:(type:string,record?:any)=>void;openInvoice:(id:string)=>void;openCustomer:(id:string)=>void;filter:string;setFilter:(s:string)=>void;query:string;setQuery:(s:string)=>void;reportFilters:ReportFilters;setReportFilters:(r:ReportFilters)=>void;ask:(s?:string)=>void;busy:boolean;refresh:()=>Promise<void>};
export function Choice({label,name,value,onChange,options,placeholder="Choose an option",disabled=false}:{label?:string;name?:string;value?:string;onChange?:(s:string)=>void;options:(string|{value:string;label:string})[];placeholder?:string;disabled?:boolean}){return <Select name={name} value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label||name} className="choice"><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent position="popper">{options.map(o=>{const v=typeof o==="string"?o:o.value;return <SelectItem key={v} value={v}>{typeof o==="string"?o:o.label}</SelectItem>})}</SelectContent></Select>}
export function Field({label,children,wide=false}: {label:string;children:ReactNode;wide?:boolean}){return <label className={"field "+(wide?"wide":"")}><span>{label}</span>{children}</label>}
export function Badge({value}:{value:string}){const green=["Paid","Delivered","Fulfilled","Approved","Active","Matched"].includes(value);const red=["Overdue","Blocked","Cancelled","Low stock","Variance"].includes(value);return <span className={"badge "+(green?"":red?"red":["Credit","Pending","Preparing","Part paid"].includes(value)?"amber":"blue")}>{green&&<Check size={11}/>} {value}</span>}
export function DataTable({headers,rows,empty="No records found",caption}:{headers:string[];rows:ReactNode[][];empty?:string;caption?:string}){if(!rows.length)return <Empty className="empty-state"><EmptyHeader><PackageOpen size={30}/><EmptyTitle>{empty}</EmptyTitle><EmptyDescription>Try a different filter or add your first record.</EmptyDescription></EmptyHeader></Empty>;return <Table className="invoice-table data-table">{caption&&<caption className="sr-only">{caption}</caption>}<TableHeader><TableRow>{headers.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((row,i)=><TableRow key={i}>{row.map((c,j)=><TableCell key={j}>{c}</TableCell>)}</TableRow>)}</TableBody></Table>}
export function Stat({label,value,detail,icon,colour=""}:{label:string;value:ReactNode;detail?:ReactNode;icon?:ReactNode;colour?:string}){return <div className="stat-card"><div className="stat-label">{label}{icon&&<span className={"stat-icon "+colour}>{icon}</span>}</div><div className="stat-value">{value}</div>{detail&&<div className="stat-footer">{detail}</div>}</div>}
export function Toolbar({children}:{children:ReactNode}){return <div className="toolbar">{children}</div>}
