"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {ArrowUpRight,ArrowRight,Bell,Building2,ChevronDown,ChevronRight,CircleHelp,CreditCard,FileBarChart2,FileText,Fuel,LayoutDashboard,Package,Plus,Search,Settings2,ShieldCheck,ShoppingBag,Sparkles,Truck,Users,CalendarDays,History,LoaderCircle,RefreshCw,LogOut,Cloud,Check} from "lucide-react";
import {Sidebar,SidebarProvider,SidebarTrigger,SidebarContent,SidebarFooter,useSidebar} from "@/components/ui/sidebar";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Command,CommandInput,CommandList,CommandEmpty,CommandGroup,CommandItem} from "@/components/ui/command";
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,DropdownMenuLabel,DropdownMenuSeparator} from "@/components/ui/dropdown-menu";
import {Toaster,toast} from "sonner";
import {type Actor,type LedgerData,type ReportFilters,today,dateShift,initials,can,outstanding,money,uid,displayDate} from "@/lib/model";
import {type AppCtx} from "./ui";
import Dashboard from "./dashboard";
import {SalesPage,CustomersPage,CreditPage,ProductsPage,DeliveriesPage,OrdersPage,FuelPage,ReportsPage,TeamPage,ActivityPage,SettingsPage,HelpPage} from "./pages";
import {EntryDialog} from "./forms";
import {InvoiceDetail,CustomerDetail,CustomerContent} from "./details";
import {Chat} from "./chat";
const navigation:{label:string;items:[string,typeof LayoutDashboard][]}[]=[{label:"WORKSPACE",items:[["Overview",LayoutDashboard],["Sales & invoices",FileText],["Customers",Users],["Credit management",CreditCard]]},{label:"OPERATIONS",items:[["Products & stock",Package],["Delivery notes",Truck],["Purchase orders",ShoppingBag],["Fuel readings",Fuel]]},{label:"MANAGEMENT",items:[["Reports",FileBarChart2],["Team & access",ShieldCheck],["Activity log",History]]}];
const customerNav:{label:string;items:[string,typeof LayoutDashboard][]}[]=[{label:"YOUR ACCOUNT",items:[["My account",LayoutDashboard],["My invoices",FileText],["Delivery notes",Truck],["My orders",ShoppingBag]]}];
function pageAllowed(page:string,a:Actor){if(a.role==="Customer")return ["My account","My invoices","Delivery notes","My orders","Help & support"].includes(page);if(page==="Reports")return can(a,"report");if(page==="Team & access")return can(a,"member");if(page==="Settings")return can(a,"settings");if(page==="Activity log")return a.role==="Super admin"||a.role==="Manager";if(page==="Overview")return can(a,"report");if(["Credit management","Fuel readings","Purchase orders","Delivery notes"].includes(page)&&a.role==="Sales staff")return false;return true}
function Nav({page,ctx}:{page:string;ctx:AppCtx}){const {setOpenMobile}=useSidebar();const overdue=new Set(ctx.data.invoices.filter(i=>i.due<today(ctx.data.business.timeZone)&&outstanding(i)>0).map(i=>i.customerId)).size;const groups=ctx.actor.role==="Customer"?customerNav:navigation;const go=(name:string)=>{ctx.navigate(name);setOpenMobile(false)};return <><div className="brand"><span className="brand-icon"><i/><i/><i/></span>ledger<span style={{color:"#14a185"}}>.</span></div><div className="workspace-switch"><span className="workspace-mark"><Building2 size={17}/></span><div><strong>{ctx.data.business.name}</strong><small>{ctx.actor.role==="Customer"?"Customer portal":"Business workspace"}</small></div></div><SidebarContent>{groups.map(g=><div key={g.label}><p className="nav-label">{g.label}</p>{g.items.filter(([name])=>pageAllowed(name,ctx.actor)).map(([name,Icon])=><button className={"nav-item "+(page===name?"active":"")} key={name} onClick={()=>go(name)}><Icon/>{name}{name==="Credit management"&&overdue>0&&<span className="count">{overdue}</span>}</button>)}</div>)}</SidebarContent><SidebarFooter style={{padding:0}}><div className="nav-bottom">{can(ctx.actor,"settings")&&<button className={"nav-item "+(page==="Settings"?"active":"")} onClick={()=>go("Settings")}><Settings2/>Settings</button>}<button className={"nav-item "+(page==="Help & support"?"active":"")} onClick={()=>go("Help & support")}><CircleHelp/>Help & support<ArrowUpRight size={14} style={{marginLeft:"auto"}}/></button></div><DropdownMenu><DropdownMenuTrigger className="user-profile"><span className="avatar">{initials(ctx.actor.name)}</span><div><strong>{ctx.actor.name}</strong><small>{ctx.actor.role}</small></div><ChevronDown size={14} style={{marginLeft:"auto"}}/></DropdownMenuTrigger><DropdownMenuContent align="start"><DropdownMenuLabel>{ctx.actor.email}</DropdownMenuLabel><DropdownMenuSeparator/><DropdownMenuItem onClick={async()=>{try{await fetch("/api/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"signout"})})}catch{}location.reload()}}><LogOut size={14}/>Sign out</DropdownMenuItem></DropdownMenuContent></DropdownMenu></SidebarFooter></>}
const subtitles:Record<string,string>={"Overview":"Here's what's happening with your business today.","Sales & invoices":"Every sale and payment, in one place.","Customers":"Know your customers. Keep their accounts in order.","Credit management":"Stay on top of balances, limits, and collections.","Products & stock":"Your products, customer rates, and available stock.","Delivery notes":"From your store to their door.","Purchase orders":"Track customer orders and their documents.","Fuel readings":"Make every liter count.","Reports":"Clear answers, from your business records.","Team & access":"The right access for the right people.","Activity log":"A record of who changed what, and when.","Settings":"Make Ledger work for your business.","Help & support":"A few simple ways to get things done.","My account":"Your account, balance, and transaction history.","My invoices":"View invoices and share payment confirmations.","My orders":"Follow your orders and request a new one."};
const primaryActions:Record<string,[string,string]>={"Overview":["New sale","sale"],"Sales & invoices":["New sale","sale"],"Customers":["Add customer","customer"],"Credit management":["Record payment","payment"],"Products & stock":["Add product","product"],"Purchase orders":["New purchase order","order"],"Fuel readings":["Add reading","reading"],"Team & access":["Add member","member"],"My orders":["Request order","orderRequest"]};
type WorkspaceState={data:LedgerData;actor:Actor;revision:number;updatedAt?:string};
export default function Workspace(){
 const [state,setState]=useState<WorkspaceState|null>(null);const [error,setError]=useState("");const [unauthorized,setUnauthorized]=useState(false);const [page,setPage]=useState("Overview");const [filter,setFilter]=useState("All");const [query,setQuery]=useState("");const [form,setForm]=useState<{type:string;record:any;key:number}|null>(null);const [invoiceId,setInvoiceId]=useState("");const [customerId,setCustomerId]=useState("");const [chatOpen,setChatOpen]=useState(false);const [chatInitial,setChatInitial]=useState<{text:string;key:number}|null>(null);const [searchOpen,setSearchOpen]=useState(false);const [busy,setBusy]=useState(false);const [reportFilters,setReportFilters]=useState<ReportFilters>({from:today().slice(0,7)+"-01",to:today()});const stateRef=useRef(state);stateRef.current=state;const savingRef=useRef(false);
 const accept=useCallback((w:WorkspaceState)=>{setState(w);setError("");setUnauthorized(false)},[]);
 const refresh=useCallback(async()=>{try{const r=await fetch("/api/workspace",{cache:"no-store"});const result=await r.json() as any;if(!r.ok){if(r.status===401)setUnauthorized(true);throw new Error(result.error)}accept(result)}catch(e){setError(e instanceof Error?e.message:"The workspace couldn't be loaded.");throw e}},[accept]);
 useEffect(()=>{void refresh().catch(()=>{});const id=setInterval(()=>{if(!savingRef.current&&document.visibilityState==="visible")void refresh().catch(()=>{})},30000);const focus=()=>{if(!savingRef.current)void refresh().catch(()=>{})};window.addEventListener("focus",focus);return()=>{clearInterval(id);window.removeEventListener("focus",focus)}},[refresh]);
 useEffect(()=>{if(state&&!pageAllowed(page,state.actor))setPage(state.actor.role==="Customer"?"My account":can(state.actor,"report")?"Overview":"Sales & invoices")},[state?.actor.role,page]);
 const navigate=useCallback((p:string,f="All",q="")=>{const current=stateRef.current;if(current&&!pageAllowed(p,current.actor)){toast.error("This page is not available for your role.");return}setPage(p);setFilter(f||"All");setQuery(q||"");if(p!=="Reports")window.scrollTo({top:0});window.history.replaceState(null,"","#"+encodeURIComponent(p))},[]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==="k"){e.preventDefault();setSearchOpen(v=>!v)}};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler)},[]);
 useEffect(()=>{if(state&&location.hash){const name=decodeURIComponent(location.hash.slice(1));if([...navigation.flatMap(g=>g.items.map(([n])=>String(n))),...customerNav.flatMap(g=>g.items.map(([n])=>String(n))),"Settings","Help & support"].includes(name)&&pageAllowed(name,state.actor))setPage(name)}},[!!state]);
 async function save(type:string,payload:Record<string,unknown>){if(savingRef.current)throw new Error("A change is already saving. Please wait.");const current=stateRef.current;if(!current)throw new Error("Workspace not loaded.");setBusy(true);savingRef.current=true;try{const r=await fetch("/api/workspace",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type,payload,revision:current.revision,requestId:uid("op")})});const result=await r.json() as any;if(!r.ok){if(r.status===409)await refresh();throw new Error(result.error||"Unable to save.")}accept(result);toast.success(type==="sale"?"Invoice and delivery note created":type==="payment"?"Payment recorded":type==="report"?"Report saved":"Changes saved");return result.result}catch(e){toast.error(e instanceof Error?e.message:"Unable to save");throw e}finally{savingRef.current=false;setBusy(false)}}
 const ask=(text="")=>{setChatOpen(true);setChatInitial({text,key:Date.now()})};
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tools=[{name:"navigate_ledger",title:"Open a Ledger page",description:"Navigate the visible workspace to an allowed business page. Does not create or change records.",inputSchema:{type:"object",properties:{page:{type:"string",enum:["Overview","Sales & invoices","Customers","Credit management","Products & stock","Reports"]}},required:["page"],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{const allowed=["Overview","Sales & invoices","Customers","Credit management","Products & stock","Reports"];if(!input||!allowed.includes(input.page)||Object.keys(input).length!==1)throw new Error("Invalid page.");const w=stateRef.current;if(!w||!pageAllowed(input.page,w.actor))throw new Error("Page is not available.");navigate(input.page);return{page:input.page}}},{name:"prepare_sales_report",title:"Preview a sales report",description:"Set the date range and open the report preview. Does not save or export a report.",inputSchema:{type:"object",properties:{from:{type:"string",format:"date"},to:{type:"string",format:"date"}},required:["from","to"],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{const w=stateRef.current;if(!w||!can(w.actor,"report"))throw new Error("Reports are not available.");const {calculateReport}=await import("@/lib/model");if(!input||typeof input.from!=="string"||typeof input.to!=="string"||Object.keys(input).length!==2)throw new Error("Two dates are required.");const report=calculateReport(w.data,input);setReportFilters(input);navigate("Reports");return{from:input.from,to:input.to,sales:report.sales,invoices:report.invoices.length}}}];for(const t of tools)try{void Promise.resolve(context.registerTool(t,{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[navigate]);
 if(!state)return <main className="loading-workspace"><div className="brand"><span className="brand-icon"><i/><i/><i/></span>ledger.</div><div className="loading-card">{error?<><h1>{unauthorized?"Your business starts here.":"Unable to load workspace"}</h1><p>{unauthorized?"This is a demo workspace for Huvathu Pvt. Sign in as Unoosh Ahmed — no password needed.":error}</p>{unauthorized?<button className="btn primary" onClick={async()=>{try{await fetch("/api/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"signin"})})}catch{}refresh().catch(()=>{})}}>Sign in as Unoosh Ahmed<ArrowRight size={16}/></button>:<button className="btn primary" onClick={()=>refresh().catch(()=>{})}><RefreshCw size={15}/>Try again</button>}</>:<><LoaderCircle className="spin" color="#087f6d"/><p>Opening your workspace…</p></>}</div></main>;
 const ctx:AppCtx={data:state.data,actor:state.actor,save,navigate,openForm:(type,record={})=>{if(!can(state.actor,type)){toast.error("Your role cannot perform this action.");return}setForm({type,record,key:Date.now()})},openInvoice:id=>{setCustomerId("");setInvoiceId(id)},openCustomer:id=>setCustomerId(id),filter,setFilter,query,setQuery,reportFilters,setReportFilters,ask,busy,refresh};
 const action=primaryActions[page];const now=today(state.data.business.timeZone);const firstName=state.actor.name.split(" ")[0];const hour=Number(new Intl.DateTimeFormat("en-GB",{timeZone:state.data.business.timeZone,hour:"numeric",hour12:false}).format(new Date()));const greeting=hour<12?"Good morning":hour<17?"Good afternoon":"Good evening";
 const low=state.data.products.filter(p=>p.stock<=p.reorder);const overdue=state.data.invoices.filter(i=>i.due<now&&outstanding(i)>0);const recentComments=state.data.comments.slice(-5).reverse();
 return <SidebarProvider style={{"--sidebar-width":"235px"} as React.CSSProperties}><Sidebar><Nav page={page} ctx={ctx}/></Sidebar><div className="main-workspace"><header className="topbar"><SidebarTrigger className="mobile-menu"/><div className="breadcrumb">Workspace<ChevronRight size={13}/><strong>{page}</strong></div><div className="topbar-actions"><button aria-label="Search workspace" className="search-trigger" onClick={()=>setSearchOpen(true)}><Search size={17}/><span>Search anything...</span><kbd>⌘ K</kbd></button><DropdownMenu><DropdownMenuTrigger asChild><button aria-label="Notifications" className="icon-button"><Bell size={19}/>{(overdue.length+low.length+recentComments.length)>0&&<i className="notify-dot"/>}</button></DropdownMenuTrigger><DropdownMenuContent className="notification-menu" align="end"><DropdownMenuLabel>Needs your attention</DropdownMenuLabel><DropdownMenuSeparator/>{state.data.business.creditReminders&&overdue.length>0&&<DropdownMenuItem onClick={()=>navigate(state.actor.role==="Customer"?"My invoices":"Credit management","Overdue")}><CreditCard size={16}/><div>{overdue.length} overdue invoices<small>{state.data.business.currency} {money(overdue.reduce((n,i)=>n+outstanding(i),0))} outstanding</small></div></DropdownMenuItem>}{state.data.business.stockAlerts&&low.length>0&&state.actor.role!=="Customer"&&<DropdownMenuItem onClick={()=>navigate("Products & stock","Low stock")}><Package size={16}/><div>{low.length} products running low<small>Check your reorder levels</small></div></DropdownMenuItem>}{recentComments.map(c=><DropdownMenuItem key={c.id} onClick={()=>ctx.openInvoice(c.invoiceId)}><FileText size={16}/><div>{c.author} commented<small>{c.text.slice(0,70)}</small></div></DropdownMenuItem>)}{!overdue.length&&!low.length&&!recentComments.length&&<DropdownMenuLabel>You're all caught up.</DropdownMenuLabel>}</DropdownMenuContent></DropdownMenu><span style={{height:23,width:1,background:"#e8edf0"}}/><span className="avatar" style={{width:31,height:31,fontSize:11}}>{initials(state.actor.name)}</span></div></header><main className="content">{error&&<div className="sync-error" role="alert">{error}<button onClick={()=>refresh().catch(()=>{})}>Retry</button></div>}<div className="page-heading"><div><h1>{page==="Overview"?greeting+", "+firstName+" ☀":page}</h1><p>{subtitles[page]}</p></div><div className="heading-actions">{page==="Overview"&&<button className="btn date-button" onClick={()=>{setReportFilters({from:now,to:now});navigate("Reports")}}><CalendarDays/>{displayDate(now)}<ChevronDown/></button>}{action&&can(state.actor,action[1])&&<button className="btn primary" onClick={()=>ctx.openForm(action[1])}><Plus/>{action[0]}</button>}</div></div>
 {page==="Overview"&&<Dashboard ctx={ctx}/>}
 {(page==="Sales & invoices"||page==="My invoices")&&<SalesPage ctx={ctx}/>}
 {page==="Customers"&&<CustomersPage ctx={ctx}/>}
 {page==="Credit management"&&<CreditPage ctx={ctx}/>}
 {page==="Products & stock"&&<ProductsPage ctx={ctx}/>}
 {page==="Delivery notes"&&<DeliveriesPage ctx={ctx}/>}
 {(page==="Purchase orders"||page==="My orders")&&<OrdersPage ctx={ctx}/>}
 {page==="Fuel readings"&&<FuelPage ctx={ctx}/>}
 {page==="Reports"&&<ReportsPage ctx={ctx}/>}
 {page==="Team & access"&&<TeamPage ctx={ctx}/>}
 {page==="Activity log"&&<ActivityPage ctx={ctx}/>}
 {page==="Settings"&&<SettingsPage ctx={ctx}/>}
 {page==="Help & support"&&<HelpPage ctx={ctx}/>}
 {page==="My account"&&<section className="panel portal-account"><CustomerContent id={state.actor.customerId} ctx={ctx}/></section>}
 <footer className="app-footer"><span><Cloud size={13}/>{busy?"Saving changes…":"Saved to your workspace"}{state.data.sample&&<span className="sample-label">Sample data</span>}</span><span>Ledger · Business made simpler</span></footer></main></div><button className="chat-fab" onClick={()=>ask()}><Sparkles size={17}/>Ask Ledger</button>
 <Chat open={chatOpen} onClose={()=>setChatOpen(false)} initial={chatInitial} ctx={ctx} onWorkspace={accept}/>
 {invoiceId&&<InvoiceDetail id={invoiceId} onClose={()=>setInvoiceId("")} ctx={ctx}/>}
 {customerId&&<CustomerDetail id={customerId} onClose={()=>setCustomerId("")} ctx={ctx}/>}
 {form&&<EntryDialog key={form.key} type={form.type} record={form.record} onClose={()=>setForm(null)} ctx={ctx}/>}
 <Dialog open={searchOpen} onOpenChange={setSearchOpen}><DialogContent className="search-dialog"><DialogHeader className="sr-only"><DialogTitle>Search workspace</DialogTitle><DialogDescription>Find a page, customer, invoice, or product.</DialogDescription></DialogHeader><Command><CommandInput placeholder="Search pages, customers, invoices…"/><CommandList><CommandEmpty>No matching records.</CommandEmpty><CommandGroup heading="Pages">{navigation.flatMap(g=>g.items).filter(([n])=>pageAllowed(n,state.actor)).map(([name,Icon])=><CommandItem key={name} value={"page "+name} onSelect={()=>{navigate(name);setSearchOpen(false)}}><Icon size={16}/>{name}</CommandItem>)}</CommandGroup><CommandGroup heading="Customers">{state.data.customers.map(c=><CommandItem key={c.id} value={c.name+" "+c.island+" "+c.phone} onSelect={()=>{ctx.openCustomer(c.id);setSearchOpen(false)}}><Users size={16}/>{c.name}<small>{c.island}</small></CommandItem>)}</CommandGroup><CommandGroup heading="Invoices">{state.data.invoices.map(i=><CommandItem key={i.id} value={i.number+" "+i.po+" "+i.date+" "+(state.data.customers.find(c=>c.id===i.customerId)?.name||"")} onSelect={()=>{ctx.openInvoice(i.id);setSearchOpen(false)}}><FileText size={16}/>{i.number}<small>{state.data.customers.find(c=>c.id===i.customerId)?.name}</small></CommandItem>)}</CommandGroup>{state.actor.role!=="Customer"&&<CommandGroup heading="Products">{state.data.products.map(p=><CommandItem key={p.id} value={p.name+" "+p.code+" "+p.barcode} onSelect={()=>{navigate("Products & stock","All",p.name);setSearchOpen(false)}}><Package size={16}/>{p.name}<small>{p.code}</small></CommandItem>)}</CommandGroup>}</CommandList></Command></DialogContent></Dialog>
 <Toaster position="top-right" richColors closeButton/>
 </SidebarProvider>;
}


