import {type LedgerData,type Invoice,type ReportFilters,calculateReport,customerName,money,displayDate,outstanding} from "./model";
const safe=(v:unknown)=>typeof v==="string"&&/^[=+@\-\t\r]/.test(v)?"'"+v:v;
export function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export async function exportRows(title:string,headers:string[],rows:unknown[][],format:string,subtitle=""){
 const filename=title.replace(/[^a-zA-Z0-9-]/g,"-").replace(/-+/g,"-").toLowerCase();
 if(format==="csv"){const csv=[headers,...rows].map(r=>r.map(v=>'"'+String(safe(v)??"").replaceAll('"','""')+'"').join(",")).join("\r\n");download(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}),filename+".csv");return}
 if(format==="xlsx"){const {default:ExcelJS}=await import("exceljs");const book=new ExcelJS.Workbook();book.creator="Ledger";book.created=new Date();const sheet=book.addWorksheet("Report");sheet.addRow([title]);sheet.addRow([subtitle]);sheet.addRow(headers);rows.forEach(r=>sheet.addRow(r.map(v=>safe(v) as any)));sheet.getRow(1).font={size:18,bold:true,color:{argb:"FF087F6D"}};sheet.getRow(3).font={bold:true,color:{argb:"FFFFFFFF"}};sheet.getRow(3).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF087F6D"}};sheet.columns.forEach(c=>c.width=23);sheet.views=[{state:"frozen",ySplit:3}];const bytes=await book.xlsx.writeBuffer();download(new Blob([bytes as BlobPart],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}),filename+".xlsx");return}
 const [{jsPDF},{default:autoTable}]=await Promise.all([import("jspdf"),import("jspdf-autotable")]);const pdf=new jsPDF({orientation:headers.length>6?"landscape":"portrait"});pdf.setTextColor(8,127,109);pdf.setFontSize(20);pdf.text(title,14,22);pdf.setTextColor(100,115,128);pdf.setFontSize(10);const lines=pdf.splitTextToSize(subtitle,pdf.internal.pageSize.getWidth()-28);pdf.text(lines,14,31);autoTable(pdf,{startY:35+lines.length*4,head:[headers],body:rows.map(r=>r.map(v=>String(v??""))),styles:{fontSize:9,cellPadding:3},headStyles:{fillColor:[8,127,109]},alternateRowStyles:{fillColor:[246,249,248]},margin:{left:14,right:14},didDrawPage:()=>{pdf.setFontSize(9);pdf.setTextColor(140);pdf.text("Ledger · "+new Date().toLocaleDateString("en-GB"),14,pdf.internal.pageSize.getHeight()-10)}});pdf.save(filename+".pdf");
}
export async function exportReport(d:LedgerData,filters:ReportFilters,format:string){const r=calculateReport(d,filters);await exportRows("Sales report "+r.from+" to "+r.to,["Invoice","Date","Customer","Payment","Sales ("+d.business.currency+")","Outstanding now"],r.invoices.map(i=>[i.number,i.date,customerName(d,i.customerId),i.method,i.total,outstanding(i)]),format,d.business.name+" | "+displayDate(r.from)+" – "+displayDate(r.to)+" | Sales "+money(r.sales)+" | Collections in period "+money(r.collections)+" | Outstanding as of end "+money(r.outstanding)+(d.sample?" | Sample data":""))}
export async function exportInvoice(d:LedgerData,i:Invoice,format="pdf"){await exportRows(i.number,["Product","Quantity","Unit","Unit price","Amount"],[...i.items.map(l=>[l.name,l.qty,l.unit,l.price,+(l.qty*l.price).toFixed(2)]),["Subtotal","","","",i.subtotal],["Discount","","","",-i.discount],["VAT ("+i.vat+"%)","","","",i.tax],["Total "+d.business.currency,"","","",i.total],["Paid","","","",i.paid],["Balance due","","","",outstanding(i)]],format,d.business.name+" | "+customerName(d,i.customerId)+" | "+displayDate(i.date)+" | Due "+displayDate(i.due)+" | "+i.method+(i.po?" | PO: "+i.po:"")+(i.remarks?" | "+i.remarks:""))}
