import {z} from "zod";
import {type Actor,type LedgerData,type Invoice,type Method,type Member,can,uid,today,validDate,round,balance,permissions,roles,calculateReport} from "./model";
const text=z.string().trim().max(500);const amount=z.coerce.number().finite().min(0).max(1e9).multipleOf(0.01,"Use at most two decimal places.");const date=z.string().refine(validDate,"Enter a valid date.");const id=z.string().min(1).max(80);
export type Operation={type:string;payload:Record<string,unknown>;requestId:string};
function need(actor:Actor,type:string){if(!can(actor,type))throw new Error("Your role does not have permission to do that.")}
export function applyOperation(original:LedgerData,actor:Actor,operation:Operation):{data:LedgerData;result:Record<string,unknown>}{
 const d=structuredClone(original),{type,payload:p}=operation;if(type==="smslog"){if(!can(actor,"payment")&&!can(actor,"credit")&&!can(actor,"report"))throw new Error("Your role cannot send messages.")}else need(actor,type);let record="",before="",after="",result:Record<string,unknown>={};const now=today(d.business.timeZone);
 if(type==="customer"){
  const v=z.object({id:id.optional(),name:text.min(2),phone:text,email:z.union([z.string().email(),z.literal("")]),island:text.min(1),address:text.default(""),business:text.default(""),tier:z.enum(["Retail","Wholesale","VIP","Contractor","School"]),limit:amount}).parse(p);
  const old=d.customers.find(c=>c.id===v.id);before=old?JSON.stringify(old):"";const row={...v,id:old?.id||uid("cus"),approved:old?.approved??true,created:old?.created||now};if(old)d.customers=d.customers.map(c=>c.id===old.id?row:c);else d.customers.push(row);record=row.name;after=JSON.stringify(row);result={id:row.id};
 }else if(type==="product"){
  const v=z.object({id:id.optional(),name:text.min(2),code:text.min(1),category:text.min(1),price:amount,cost:amount,stock:amount,reorder:amount,unit:text.min(1),barcode:text.default(""),rates:z.record(amount).default({})}).parse(p);
  if(d.products.some(x=>x.code.toLowerCase()===v.code.toLowerCase()&&x.id!==v.id))throw new Error("That product code is already in use.");const old=d.products.find(x=>x.id===v.id);if(v.id&&!old)throw new Error("Product not found.");before=old?JSON.stringify(old):"";const row={...v,id:old?.id||uid("prd"),rates:{...v.rates,Retail:v.price}};if(old)d.products=d.products.map(x=>x.id===old.id?row:x);else d.products.push(row);record=row.name;after=JSON.stringify(row);result={id:row.id};
 }else if(type==="sale"){
  const v=z.object({customerId:id,date,due:date,method:z.enum(["Cash","Bank transfer","Credit"]),discount:amount,vat:amount.max(100),po:text.default(""),remarks:text.default(""),items:z.array(z.object({productId:id,qty:amount.positive(),price:amount.optional()})).min(1).max(100)}).parse(p);
  if(v.date>now)throw new Error("Invoice date cannot be in the future.");if(v.due<v.date)throw new Error("Due date must be on or after the invoice date.");const customer=d.customers.find(c=>c.id===v.customerId);if(!customer)throw new Error("Choose a valid customer.");
  const required=new Map<string,number>();for(const l of v.items)required.set(l.productId,(required.get(l.productId)||0)+l.qty);
  for(const [pid,qty] of required){const product=d.products.find(x=>x.id===pid);if(!product)throw new Error("A selected product no longer exists.");if(product.stock<qty)throw new Error(product.name+" has only "+product.stock+" "+product.unit+" available.");}
  const items=v.items.map(l=>{const product=d.products.find(x=>x.id===l.productId)!;const rate=product.rates[customer.tier]??product.price;if(l.price!==undefined&&l.price!==rate&&!can(actor,"product"))throw new Error("Your role must use the customer's assigned product rate.");return{productId:product.id,name:product.name,qty:l.qty,price:l.price??rate,cost:product.cost,unit:product.unit}});
  const subtotal=round(items.reduce((n,l)=>n+round(l.qty*l.price),0));if(v.discount>subtotal)throw new Error("Discount cannot exceed the subtotal.");const tax=round((subtotal-v.discount)*v.vat/100),total=round(subtotal-v.discount+tax);
  if(v.method==="Credit"&&(!customer.approved||balance(d,customer.id)+total>customer.limit))throw new Error(!customer.approved?"Credit is blocked for this customer.":"This sale would exceed the customer's available credit.");
  const n=d.invoices.reduce((m,i)=>Math.max(m,Number(i.number.replace(/\D/g,""))||0),100)+1;
  const invoice:Invoice={...v,id:uid("inv"),number:"INV-"+String(n).padStart(4,"0"),items,subtotal,tax,total,paid:v.method==="Credit"?0:total,createdBy:actor.name};d.invoices.unshift(invoice);
  for(const [pid,qty] of required){const product=d.products.find(x=>x.id===pid)!;product.stock=round(product.stock-qty)}
  for(const reading of d.readings.filter(r=>r.date===invoice.date&&required.has(r.productId))){reading.recordedLiters=round(d.invoices.filter(i=>i.date===reading.date).reduce((n,i)=>n+i.items.filter(l=>l.productId===reading.productId).reduce((s,l)=>s+l.qty,0),0));reading.difference=round(reading.liters-reading.recordedLiters)}
  if(invoice.paid)d.payments.unshift({id:uid("pay"),invoiceId:invoice.id,date:invoice.date,amount:invoice.paid,method:invoice.method,reference:"At sale"});
  d.deliveries.unshift({id:uid("dn"),number:"DN-"+String(n).padStart(4,"0"),invoiceId:invoice.id,customerId:invoice.customerId,po:invoice.po,date:invoice.date,vehicle:"",driver:"",signature:"",status:"Preparing"});record=invoice.number;after=JSON.stringify(invoice);result={id:invoice.id,number:invoice.number};
 }else if(type==="payment"){
  const v=z.object({invoiceId:id,date,amount:amount.positive(),method:z.enum(["Cash","Bank transfer"]),reference:text.default("")}).parse(p);const invoice=d.invoices.find(i=>i.id===v.invoiceId);if(!invoice)throw new Error("Invoice not found.");if(v.date<invoice.date||v.date>now)throw new Error("Payment date must be between the invoice date and today.");if(v.amount>round(invoice.total-invoice.paid))throw new Error("Payment cannot exceed the remaining balance.");before=JSON.stringify({paid:invoice.paid});invoice.paid=round(invoice.paid+v.amount);d.payments.unshift({...v,id:uid("pay")});record=invoice.number;after=JSON.stringify({paid:invoice.paid,payment:v});result={id:invoice.id};
 }else if(type==="delivery"){
  const v=z.object({id,status:z.enum(["Preparing","In transit","Delivered"]),vehicle:text,driver:text,signature:text.default("")}).parse(p);const row=d.deliveries.find(x=>x.id===v.id);if(!row)throw new Error("Delivery not found.");if(v.status==="Delivered"&&!v.signature)throw new Error("Enter the recipient's name to confirm delivery.");before=JSON.stringify(row);Object.assign(row,v);record=row.number;after=JSON.stringify(row);
 }else if(type==="order"||type==="orderRequest"){
  const v=z.object({id:id.optional(),number:text.min(1),customerId:id,date,amount,notes:text,status:z.enum(["Pending","Approved","Fulfilled","Cancelled"])}).parse(p);if(!d.customers.some(c=>c.id===v.customerId))throw new Error("Customer not found.");if(type==="orderRequest"&&(v.customerId!==actor.customerId||v.id))throw new Error("You can request orders only for your own account.");if(d.orders.some(x=>x.number.toLowerCase()===v.number.toLowerCase()&&x.id!==v.id))throw new Error("That PO number is already in use.");const old=d.orders.find(x=>x.id===v.id);if(v.id&&!old)throw new Error("Purchase order not found.");before=old?JSON.stringify(old):"";const row={...v,id:old?.id||uid("po"),status:type==="orderRequest"?"Pending":v.status};if(old)d.orders=d.orders.map(x=>x.id===old.id?row:x);else d.orders.unshift(row);record=row.number;after=JSON.stringify(row);result={id:row.id};
 }else if(type==="reading"){
  const v=z.object({date,productId:id,start:amount,end:amount,notes:text.default("")}).parse(p);if(v.date>now)throw new Error("Choose today or an earlier date.");const product=d.products.find(x=>x.id===v.productId&&x.category==="Fuel");if(!product)throw new Error("Choose a fuel product.");if(v.end<v.start)throw new Error("Closing meter must be greater than or equal to opening meter.");if(d.readings.some(r=>r.date===v.date&&r.productId===v.productId))throw new Error("A reading already exists for this product and date.");const previous=d.readings.filter(r=>r.productId===v.productId&&r.date<v.date).sort((a,b)=>b.date.localeCompare(a.date))[0];if(previous&&previous.end!==v.start&&!v.notes)throw new Error("Opening meter differs from the previous closing meter. Add a note explaining the difference.");const recordedLiters=round(d.invoices.filter(i=>i.date===v.date).reduce((n,i)=>n+i.items.filter(l=>l.productId===v.productId).reduce((s,l)=>s+l.qty,0),0));const liters=round(v.end-v.start);const row={...v,id:uid("fuel"),liters,recordedLiters,difference:round(liters-recordedLiters)};d.readings.unshift(row);record=product.name+" · "+v.date;after=JSON.stringify(row);
 }else if(type==="credit"){
  const v=z.object({customerId:id,limit:amount,approved:z.boolean()}).parse(p);const c=d.customers.find(x=>x.id===v.customerId);if(!c)throw new Error("Customer not found.");before=JSON.stringify({limit:c.limit,approved:c.approved});Object.assign(c,{limit:v.limit,approved:v.approved});record=c.name;after=JSON.stringify(v);
 }else if(type==="expense"){
  const v=z.object({date,category:text.min(1),amount:amount.positive(),notes:text}).parse(p);if(v.date>now)throw new Error("Expense date cannot be in the future.");const row={...v,id:uid("exp")};d.expenses.unshift(row);record=v.category;after=JSON.stringify(row);
 }else if(type==="report"){
  const v=z.object({name:text.min(1),from:date,to:date,customerId:text.default(""),productId:text.default(""),method:text.default(""),island:text.default(""),salesperson:text.default("")}).parse(p);calculateReport(d,v);const row={...v,id:uid("rep"),created:new Date().toISOString(),createdBy:actor.name};d.reports.unshift(row);record=row.name;after=JSON.stringify(row);result={id:row.id,report:row};
 }else if(type==="member"){
  const v=z.object({id:id.optional(),name:text.min(2),email:z.string().email().transform(x=>x.toLowerCase()),role:z.enum(["Manager","Sales staff","Accounts","Customer"]),customerId:text.default(""),permissions:z.array(z.string()).default([])}).parse(p);if(v.role==="Customer"&&!d.customers.some(c=>c.id===v.customerId))throw new Error("Link the customer account first.");if(v.email===actor.email.toLowerCase())throw new Error("The workspace owner's access cannot be changed here.");if(v.permissions.some(x=>!permissions["Super admin"].includes(x)))throw new Error("Invalid permission.");if(d.members.some(m=>m.email===v.email&&m.id!==v.id))throw new Error("This email already has access.");const old=d.members.find(m=>m.id===v.id);before=old?JSON.stringify(old):"";const member:Member={...v,id:old?.id||uid("member"),permissions:v.role==="Customer"?[]:v.permissions};if(old)d.members=d.members.map(m=>m.id===old.id?member:m);else d.members.push(member);record=v.email;after=JSON.stringify(member);
 }else if(type==="settings"){
  const v=z.object({name:text.min(2),currency:z.enum(["MVR","USD","EUR","GBP"]),timeZone:z.string().refine(x=>{try{new Intl.DateTimeFormat("en",{timeZone:x});return true}catch{return false}},"Choose a valid timezone."),vat:amount.max(100),creditReminders:z.boolean(),stockAlerts:z.boolean()}).parse(p);before=JSON.stringify(d.business);d.business=v;record="Business settings";after=JSON.stringify(v);
 }else if(type==="comment"){
  const v=z.object({invoiceId:id,text:text.min(1)}).parse(p);const invoice=d.invoices.find(i=>i.id===v.invoiceId);if(!invoice||(actor.role==="Customer"&&invoice.customerId!==actor.customerId))throw new Error("Invoice not found.");d.comments.push({...v,id:uid("comment"),customerId:invoice.customerId,author:actor.name,date:new Date().toISOString()});record=invoice.number;after=v.text;
 }else if(type==="attachment"){
  const v=z.object({id,entityId:id,customerId:id,name:text.min(1),size:amount.max(5*1024*1024),mime:text,author:text,date:z.string()}).parse(p);const entity=d.invoices.find(i=>i.id===v.entityId)||d.orders.find(i=>i.id===v.entityId);if(!entity||entity.customerId!==v.customerId||(actor.role==="Customer"&&v.customerId!==actor.customerId))throw new Error("Record not found.");d.attachments.push(v);record=v.entityId;after=v.name;
 }else if(type==="smslog"){
  const v=z.object({entries:z.array(z.object({date:text.default(""),kind:z.enum(["payment","reminder","custom","sale"]),invoiceId:text.default(""),customerId:text.default(""),phone:text.default(""),message:z.string().trim().max(2000),status:z.enum(["sent","failed"]),providerId:text.default(""),error:text.default("")})).max(200).default([]),lastReminderRun:text.optional()}).parse(p);
  if(!Array.isArray(d.sms))d.sms=[];for(const e of v.entries)d.sms.unshift({...e,id:uid("sms"),by:actor.name});if(d.sms.length>500)d.sms.length=500;if(v.lastReminderRun)d.reminders={...(d.reminders||{}),lastRun:v.lastReminderRun};record="SMS";after=v.entries.length+" message"+(v.entries.length===1?"":"s");result={count:v.entries.length,sent:v.entries.filter(e=>e.status==="sent").length};
 }else{throw new Error("Unsupported action.")}
 d.audit.unshift({id:operation.requestId,date:new Date().toISOString(),actor:actor.name,action:type==="sale"?"Invoice created":type==="payment"?"Payment recorded":type==="report"?"Report generated":type==="smslog"?"SMS notification":type.charAt(0).toUpperCase()+type.slice(1)+" saved",record,before,after});return{data:d,result};
}
export function visibleData(d:LedgerData,a:Actor):LedgerData{
 const copy=structuredClone(d);
 if(a.role==="Customer"){
  const cid=a.customerId;copy.customers=copy.customers.filter(c=>c.id===cid);copy.invoices=copy.invoices.filter(i=>i.customerId===cid);copy.payments=copy.payments.filter(p=>copy.invoices.some(i=>i.id===p.invoiceId));copy.deliveries=copy.deliveries.filter(x=>x.customerId===cid);copy.orders=copy.orders.filter(x=>x.customerId===cid);copy.comments=copy.comments.filter(x=>x.customerId===cid);copy.attachments=copy.attachments.filter(x=>x.customerId===cid);copy.readings=[];copy.reports=[];copy.expenses=[];copy.audit=[];copy.members=[];
 }
 if(!can(a,"payment")&&!can(a,"credit")&&!can(a,"report"))copy.sms=[];
 if(!can(a,"member"))copy.members=[];
 if(!can(a,"report")){copy.products=copy.products.map(p=>({...p,cost:0}));copy.invoices=copy.invoices.map(i=>({...i,items:i.items.map(l=>({...l,cost:0}))}));copy.expenses=[];copy.reports=[];if(a.role!=="Customer")copy.audit=[];}
 return copy;
}
